root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "./tailwindcss-linux-x64 -i ./src/input.css -o ./public/style.css && templ generate && go build -o ./tmp/main ./cmd/makerthon"
exclude_dir = ["assets", "tmp", "vendor", "public"]
exclude_regex = [".*_templ.go"]
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
log = "build-errors.log"
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"
