services:
  server:
    image: makerthon
    build: .
    volumes:
      - ./cmd:/go/src/makerthon/cmd
      - ./public:/go/src/makerthon/public
      - ./models:/go/src/makerthon/models
      - ./views:/go/src/makerthon/views
      - ./controllers:/go/src/makerthon/controllers
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_DNS=${POSTGRES_DNS}
      - BASE_URL=${BASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - VERIFICATION_URL=${VERIFICATION_URL}
      - DOCUMENT_ANALYSIS_API=${DOCUMENT_ANALYSIS_API}
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: exampledb
      POSTGRES_DB: vlu_makerthon
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080