// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
)

func VerificationEmailTemplate(username, code string, expiryMinutes int, verificationURL string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"UTF-8\"><title>Xác nhận tài khoản QuizCreator của bạn</title><style>\n            body {\n                font-family: Arial, sans-serif;\n                line-height: 1.6;\n                color: #333;\n                max-width: 600px;\n                margin: 0 auto;\n            }\n            .container {\n                background-color: #f8f9fa;\n                padding: 20px;\n                border-radius: 5px;\n                margin: 20px 0;\n            }\n            .header {\n                color: #4f46e5;\n            }\n            .code-box {\n                background-color: #ffffff;\n                border: 1px solid #e5e7eb;\n                border-radius: 5px;\n                padding: 20px;\n                margin: 20px 0;\n                text-align: center;\n            }\n            .verification-code {\n                font-size: 32px;\n                font-weight: bold;\n                letter-spacing: 5px;\n                color: #4f46e5;\n                margin: 15px 0;\n            }\n            .button {\n                background-color: #4f46e5;\n                color: white;\n                padding: 12px 24px;\n                text-decoration: none;\n                border-radius: 5px;\n                font-weight: bold;\n                display: inline-block;\n                margin: 20px 0;\n            }\n            .footer {\n                text-align: center;\n                padding: 20px;\n                color: #6b7280;\n                font-size: 12px;\n            }\n        </style></head><body><div class=\"container\"><h2 class=\"header\">Xin chào ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/email_template.templ`, Line: 65, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, ",</h2><p>Cảm ơn bạn đã đăng ký tài khoản QuickQuiz. Để hoàn tất quá trình đăng ký, vui lòng xác thực địa chỉ email của bạn.</p><div class=\"code-box\"><h3 style=\"margin-top: 0;\">Mã xác thực của bạn là:</h3><div class=\"verification-code\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(code)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/email_template.templ`, Line: 70, Col: 53}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><p style=\"margin-bottom: 0; color: #6b7280;\">Mã này sẽ hết hạn sau ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", expiryMinutes))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/components/email_template.templ`, Line: 71, Col: 125}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " phút.</p></div><p>Nếu bạn không đăng ký tài khoản, vui lòng bỏ qua email này.</p><p>Trân trọng,<br>Đội ngũ QuickQuiz</p></div><div class=\"footer\"><p>© 2025 QuickQuiz</p></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
